/*
 * Copyright (c) 2008 Xilinx, Inc.  All rights reserved.
 *
 * Xilinx, Inc.
 * XILINX IS PROVIDING THIS DESIGN, CODE, OR INFORMATION "AS IS" AS A
 * COURTESY TO YOU.  BY PROVIDING THIS DESIGN, CODE, OR INFORMATION AS
 * ONE POSSIBLE   IMPLEMENTATION OF THIS FEATURE, APPLICATION OR
 * STANDARD, XILINX IS MAKING NO REPRESENTATION THAT THIS IMPLEMENTATION
 * IS FREE FROM ANY CLAIMS OF INFRINGEMENT, AND YOU ARE RESPONSIBLE
 * FOR OBTAINING ANY RIGHTS YOU MAY REQUIRE FOR YOUR IMPLEMENTATION.
 * XILINX EXPRESSLY DISCLAIMS ANY WARRANTY WHATSOEVER WITH RESPECT TO
 * THE ADEQUACY OF THE IMPLEMENTATION, INCLUDING BUT NOT LIMITED TO
 * ANY WARRANTIES OR REPRESENTATIONS THAT THIS IMPLEMENTATION IS FREE
 * FROM CLAIMS OF INFRINGEMENT, IMPLIED WARRANTIES OF MERCHANTABILITY
 * AND FITNESS FOR A PARTICULAR PURPOSE.
 *
 */

#ifndef __PLATFORM_H_
#define __PLATFORM_H_

extern int cpuId;


/* Memory Addresses */
#define DDR_OFFSET	 	0x10000000
#define DDR_SIZE  		0x10000000


// todo Check BRAM size during transfert
#define BRAM_SIZE 0x00008000

#define MBOX_CTRL_ADDR	0x40000000
#define MBOX_INFO_ADDR 	0x40010000
#define GPIO_ADDR 		0x40020000
#define INTC_ADDR 		0x40030000
#define TIMER_ADDR 		0x40040000
#define CDMA_ADDR 		0x40050000

#define MDM_ADDR 		0x40060000

void init_platform();
void cleanup_platform();


#endif
