
export OMP_DIR=/opt/ti_k2_v6_0_1_mcsdk_3_1_1_4/openmp_dsp_2_01_16_03/packages
export XDC_DIR=/opt/ti_k2_v6_0_1_mcsdk_3_1_1_4/xdctools_3_25_06_96
export XDCCGROOT=/opt/ti_k2_v6_0_1_mcsdk_3_1_1_4/ccsv6/tools/compiler/ti-cgt-c6000_8.0.3

export USE_BIOS=1
export BIOS_DIR=/opt/ti_k2_v6_0_1_mcsdk_3_1_1_4/bios_6_37_03_30/packages
export IPC_DIR=/opt/ti_k2_v6_0_1_mcsdk_3_1_1_4/ipc_3_22_02_11/packages

export ULM_DIR="/opt/ti_k2_v6_0_1_mcsdk_3_1_1_4/mcsdk-hpc_03_00_01_12/images/tmp/usr/share/ti/ulm"
export DSP_DIR=/opt/ti_k2_v6_0_1_mcsdk_3_1_1_4/dsplib_c66x_3_2_0_1/packages

export OMP_TARGET=C6636

export C6636_PDK_DIR=/opt/ti_k2_v6_0_1_mcsdk_3_1_1_4/pdk_keystone2_3_01_01_04/packages
export C6670_PDK_DIR= 
export C6678_PDK_DIR=/opt/ti_k2_v6_0_1_mcsdk_3_1_1_4/pdk_C6678_1_1_2_6/packages
export C6657_PDK_DIR= 